apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZERCd1lFeEpVMVl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpFeU1qTXhNelE0TXpoYUZ3MHpNekV5TWpBeE16VXpNemhhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN5cmxxa2ZscnU1QXR1UjV6QVkzWHM5ZExzTmVPc1FoVE40aFFxalg0SnhwNzJLaGF5S3gwRHZKa0YKS0w3WFVZdWJOQzE2eWdKMkthV2trNjVuSzkvbHZJKzJXeHNibUMvbm1OQmIzTm5Tbk93MTJzcGpvcmMzWnU5KworNU01TmRtU3RMRXpYKzlGVkhvaE45YUhlK29xNVpvZG9GMXBWbUtEWUNtSVY3SVJSZStaWGtSb2JJUFN1cFdUCmY5bmIwZXh3RlZMZzJtS0RvTkVjMytIRCtxQXdEQzkzcSt5MXV5VWVtWi9KREFTV2FCaVphcEMxMElRVWkvTVEKZUErSFJqbHllSFZ3N1pCSXVEa3BvRGphRVN4T0FnL3IzenhqU0FmRDREMERiQUpFZTg2YVdCWW5DbmZ4Y21WWQptQXZEcGowVEJlTWhXRmxLRSttaDBYRTU4bENCQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRUWhzMnh3QnZZSC9qQ3E4dG1VSDNqWmR3bW5qQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ05qTDRKbmk1UwpuaFFtQnBPRFRZeStXT3dWVk56MG0wRm5NQVBaZzVncEdZMmQrRzI3RzB3cHhlbUNicDk2dUQ3aXRuLzNMRnViCnpHU3JqZWhZZjR4WldmU1dJMW8yZmQ4eHBFbFNTU3BHUUs5WGVrbUdGUEdzTjYrU0laeXhndFJxYjJ4VnFZR0kKMDM4aE5DSTFUTkRHY3BkdTlwenRNeTJ3cWNnNGpBejRMZ0o3MlNpY1JDMmhyRUYzTW82TjJEQWoxQ0tRcVlPegpNdlo5M0xOL2FPQzdjMFo5dmpLb2E5dURlNndNWDBLMmoxdTk2UjRvVTVCTWFPeVQ4eW9vdkpBQnkvR2x5eTFECnJXYVlzNytVMzRkUGdhelRKa2ZwMmFSWmY0S2FBRkhOclRXeXVRZFNXUEQ5Y0RyaTBaSXI0OEJjNFdUT1R5TXIKWWJ6V3FXMFpHUWhYCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://5653989009A49224311A68486EBB1FFB.gr7.eu-central-1.eks.amazonaws.com
  name: arn:aws:eks:eu-central-1:300732800381:cluster/actimize_eks
contexts:
- context:
    cluster: arn:aws:eks:eu-central-1:300732800381:cluster/actimize_eks
    user: arn:aws:eks:eu-central-1:300732800381:cluster/actimize_eks
  name: arn:aws:eks:eu-central-1:300732800381:cluster/actimize_eks
current-context: arn:aws:eks:eu-central-1:300732800381:cluster/actimize_eks
kind: Config
preferences: {}
users:
- name: arn:aws:eks:eu-central-1:300732800381:cluster/actimize_eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-central-1
      - eks
      - get-token
      - --cluster-name
      - actimize_eks
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: default
